Vagrant.configure("2") do |config|
    
    config.vm.box = "spox/ubuntu-arm"
    config.vm.box_version = "1.0.0"
    config.vm.network "forwarded_port", guest: 3000, host: 8080
    # config.vm.network "private_network", ip: "192.168.56.11"
    config.vm.network "public_network"
    
    config.vm.provider "vmware_desktop" do |vmware|
        vmware.gui = true
        vmware.allowlist_verified = true
        vmware.memory = 4096
        vmware.cpus = 2
    end

    # config.vm.provision "shell", path: "provision.sh"
end