apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80                   # Port to expose the service (like public-facing)
      targetPort: 3000           # Port inside the pod/container
      nodePort: 30080            # Optional: exposes on host's IP:30080